###############################################################################
# Description: Entry point to install Docker, Openshift Origin, Gluster, and Heketi
# Author: John Deng ( john.deng@qq.com )
# Last update: 2017-01-29
###############################################################################
# Usage:
# ansible-playbook main.yml --extra-vars "admin_password='you-admin-password' force_install_docker=true ansible_profile=dev"
#
---

- name: post installation
  hosts: all
  become: no
  gather_facts: no

  tasks:
  - name: set password for admin
    shell: htpasswd -b /etc/origin/master/htpasswd admin {{ admin_password }} chdir=/etc/origin/master 
    when: "'masters' in group_names"

  - name: Login to openshift cluster
    become: yes
    become_user: root
    command: oc login https://{{ groups.masters[0] }}:8443 --insecure-skip-tls-verify=true --username=admin --password={{ admin_password }}
    args:
        chdir: /root
        creates: /root/.kube/config
    when: "'client' in group_names"

  - name: Config masters
    include: playbook/masters/config.yml
    when: "'masters' in group_names"

  - name: Config storages
    include: playbook/storages/config.yml
    when: "'storages' in group_names"

  - name: Deploy Gluster and Heketi
    include: playbook/client/heketi.yml
    when: "'client' in group_names"

###############################################################################
# Done    
###############################################################################