#!/bin/bash
###############################################################################
# Project: hi-cli
# Description: The cross platform development toolkit - hi-cli
# Author: John Deng (john.deng@outlook.com)
#
# Copyright (c) 2014-2017 John Deng (john.deng@outlook.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: John Deng (john.deng@outlook.com)
# Updated: Thu Mar 30 21:24:46 CST 2017
# Module: openshift
# Submodule: 
# Command: install
###############################################################################

source "${HI_CLI_HOME}/bin/colors"
source "${HI_CLI_HOME}/bin/clap"
source "${HI_CLI_HOME}/bin/logging"
source "${HI_CLI_HOME}/bin/utils"
###############################################################################
function run() {
  hosts_conf=
  if [ -f ${PWD}/hosts.conf ]; then
    hosts_conf="-i ${PWD}/hosts.conf"
  fi
  if [ -f ${HOME}/.openshift/hosts.conf ]; then
    hosts_conf="-i ${HOME}/.openshift/hosts.conf"
  fi
  
  ansible ${hosts_conf} all -m ping
  
  cli="exit"
  if prompt_yesorno "Openshift is about to uninstall, do you wish to do it? [yes/no]"; then
    cli="ansible-playbook ${hosts_conf} ${module_dir}/openshift-ansible/playbooks/adhoc/uninstall.yml"
    pushd "${module_dir}" > /dev/null
  
    if [ ! -d "${module_dir}/openshift-ansible" ]; then
      git clone https://github.com/openshift/openshift-ansible.git
    fi

    ${cli}

    result=$?

    popd > /dev/null

    result=$?
  else
    exit
  fi

  eval $1="\${result}"
  eval $2="\${cli}"
}

###############################################################################
