#!/bin/bash
###############################################################################
# Project: hi-cli
# Description: The cross platform development toolkit - hi-cli
# Author: John Deng (john.deng@outlook.com)
#
# Copyright (c) 2014-2017 John Deng (john.deng@outlook.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: John Deng (john.deng@outlook.com)
# Updated: Thu Mar 30 21:24:46 CST 2017
# Module: openshift
# Submodule: 
# Command: install
###############################################################################

source "${HI_CLI_HOME}/bin/colors"
source "${HI_CLI_HOME}/bin/clap"
source "${HI_CLI_HOME}/bin/logging"
source "${HI_CLI_HOME}/bin/utils"
source "${module_dir}/play"
###############################################################################

function run() {

  cli="hi openshift update"

  if [ -f ${PWD}/hosts.conf ]; then
    hosts_conf="-i ${PWD}/hosts.conf"
  fi
  if [ -f ${HOME}/.openshift/hosts.conf ]; then
    hosts_conf="-i ${HOME}/.openshift/hosts.conf"
  fi

  if [ "${openshift_update_version}" == "" ]; then
    openshift_update_version="v3_5"
  fi

  ansible_verbose_mode=
  if [ "${verbose}" != "" ];
  then
    ansible_verbose_mode="-v"
  fi
  if [ "${more}" != "" ];
  then
    ansible_verbose_mode="-vvv"
  fi

  ansible-playbook ${hosts_conf} ${module_dir}/openshift-ansible/playbooks/byo/openshift-cluster/upgrades/${openshift_update_version}/upgrade.yml ${ansible_verbose_mode}

  result="$?"

  eval $1="\${result}"
  eval $2="\${cli}"
}
###############################################################################
