#!/bin/bash
###############################################################################
# Project: hi-cli
# Description: The cross platform development toolkit - hi-cli
# Author: John Deng (john.deng@outlook.com)
#
# Copyright (c) 2014-2017 John Deng (john.deng@outlook.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: John Deng (john.deng@outlook.com)
# Updated: Thu Mar 30 21:24:46 CST 2017
# Module: openshift
# Submodule: 
# Command: deploy heketi
###############################################################################

source "${HI_CLI_HOME}/bin/colors"
source "${HI_CLI_HOME}/bin/logging"
###############################################################################

function run() {

  cli="hi openshift deploy heketi"

  oc whoami 2>/dev/null
  if [ $? != 0 ]; then
    oc login
  fi
  
  if ! prompt_yesorno "All persistences will be erased, do you wish to deploy heketi $(oc status | grep server)? [yes/no]"; then
    log_warn "Canceled"
    exit
  fi

  topology_json_file="${PWD}/topology.json"
  if [ ! -f "${topology_json_file}" ]; then
    log_warn "${topology_json_file} not found!"
    exit
  fi

  which heketi-cli &2>/dev/null
  if [ $? != 0 ]; then
    log_warn "heketi-cli is not found, please download it from https://github.com/heketi/heketi/releases and put to /usr/bin/"
    exit
  fi

  gk_deploy_verbose_mode=""
  if [ "${verbose}" != "" ];
  then
    gk_deploy_verbose_mode="-v"
  fi

  gk_deploy_load=""
  if [ "${load}" != "" ];
  then
    gk_deploy_load="--load"
  fi

  gk_deploy_abort=""
  if [ "${abort}" != "" ];
  then
    if prompt_yesorno "Do you wish to abort heketi $(oc status | grep server)? [yes/no]"; then
      gk_deploy_abort="--abort"
    fi
  fi
  
  if [ ! -d "${module_dir}/gluster-kubernetes" ]; then
    git clone ${gluster_kubernetes_url} ${module_dir}/gluster-kubernetes  
  fi

  cp "${topology_json_file}" ${module_dir}/gluster-kubernetes/deploy/

  pushd "${module_dir}/gluster-kubernetes/deploy/" > /dev/null
    cli="./gk-deploy --admin-key=${admin_key} --user-key=${user_key} -g ${gk_deploy_verbose_mode} ${gk_deploy_load} ${gk_deploy_abort} ${gk_deploy_overrit} " 
    log_debug "${cli}"

    ${cli}
    result="$?"
  popd

  eval $1="\${result}"
  eval $2="\${cli}"
}
###############################################################################
