###############################################################################
# install packages
###############################################################################

- name: Ensure Centos 7
  shell: echo $(more /etc/redhat-release | grep "CentOS Linux release 7" | wc -l)
  register: os_release
  failed_when: os_release.stdout == 0

- name: Ensure below services are disabled
  systemd: name={{ item }} enabled=no
  with_items:
  - firewalld
  - iptables

- name: Enable selinux
  selinux: policy=targeted state=enforcing

- name: install packages
  yum: name={{ item }} state=present
  with_items:
  - epel-release
  - centos-release-gluster
  - wget 
  - git 
  - net-tools 
  - bind-utils 
  - iptables-services 
  - bridge-utils 
  - bash-completion
  - dnsmasq
  - ncurses-term
  - python-pip
  - pyOpenSSL
  - NetworkManager
  - heketi-client
  - heketi-templates

- set_fact: git_branch='master'
  when: git_branch is undefined

- name: fetch hi-cli from github
  git: repo="https://github.com/hi-cli/hi-cli.git"
        dest=/usr/local/hi-cli
        version=master
        update=yes

- name: install hi-cli
  shell: /usr/local/hi-cli/bin/install /usr/local/hi-cli

- name: Ensure hostname set
  hostname: name={{ inventory_hostname }}
  when: not inventory_hostname|match('(\d{1,3}\.){3}\d{1,3}')

- name: install hi module {{ item }}
  shell: hi package install {{ item }} force
  environment:
    HI_CLI_HOME: "/usr/local/hi-cli"
    PATH: "/usr/local/hi-cli/bin:{{ ansible_env.PATH }}"
  with_items:
  - centos
  - docker

- name: "hi install ..."
  shell: hi centos install
  environment:
    HI_CLI_HOME: "/usr/local/hi-cli"
    PATH: "/usr/local/hi-cli/bin:{{ ansible_env.PATH }}"
