- hosts: all
  become: no
  gather_facts: no
  tasks:
  - name: Download repo
    get_url:
      url: "{{ centos_repo_mirror }}{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: 0644
    with_items:
    - src: offline.repo
      dest: /etc/yum.repos.d/CentOS-Base.repo
    - src: openshift-ansible-CentOS-SIG-PaaS
      dest: /etc/pki/rpm-gpg/
    - src: openshift-ansible-centos-paas-sig.repo
      dest: /etc/yum.repos.d/    

  - name: Clean repo
    command: yum clean all
    
  - name: Update repo
    command: yum makecache
