- hosts: nodes
  become: no
  gather_facts: no
  vars:
    docker_dev: "{{ docker_storage_device | default('/dev/sdb') }}"
  tasks:
  - name: Install docker
    shell: env hi docker install all new storage={{ docker_dev }}
