---
- hosts: storages
  become: no
  gather_facts: no
  tasks:
  
  - name: Ensure below services are disabled
    systemd: name={{ item }} enabled=no
    with_items:
    - firewalld
    ignore_errors: command_result is defined and "'Could not find the requested service' in command_result.stderr"
  
  - name: Ensure below services are enabled
    systemd: name={{ item }} enabled=yes
    with_items:
    - iptables
 
  - name: debug groups.storages
    debug: msg={{ groups.storages }}

  - name: iptables {{ item }}
    command: iptables -A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m {{ item.match }} --dport {{ item.port }} -j ACCEPT
    with_items:
    - {port: "24007", match: "tcp"}
    - {port: "24008", match: "tcp"}
    - {port: "2222", match: "tcp"}
    - {port: "49152:49251", match: "multiport"}

  - name: save iptables
    command: service iptables save


# TODO: service and endpoint ?

