---
- hosts: storages
  become: no
  gather_facts: no
  tasks:
  
  - name: debug groups.storages
    debug: msg={{ groups.storages }}

  - name: "firewall {{ item }}"
    command: firewall-cmd --zone=public --add-port={{ item.port }}/{{ item.protocol }} --permanent
    with_items:
    - {port: "24007", protocol: "tcp"}
    - {port: "24008", protocol: "tcp"}
    - {port: "2222", protocol: "tcp"}
    - {port: "49152-49251", protocol: "tcp"}

  - name: reload firewall
    command: firewall-cmd --reload

